config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :admins do
    get "delete"
    get "booking"
  end
  get "list_admin", to: "admins#list_admin"
  get "list_user", to: "admins#list_user"
  resources :tours do
    get "delete"
  end
  root "mytours#home"
  post "/rate" , to: "rater#create", as: "rate"
  get "/booked", to: "bookings#booked"
  resources :users
  resources :mytours
  resources :bookings do
    get "delete"
  end
  resources :reviews, only: [:create, :destroy]
  resources :admins
end

app/controllers/mytours_controller.rb
class MytoursController < ApplicationController
  def home; end

  def index
    @search = Tour.infotour.ransack params[:q]
    @search.sorts = %w(destination price) if @search.sorts.empty?
    @tours = @search.result.order(:id).page(params[:page]).per Settings.paginate.per_page
    @toptours = RatingCache.connect_tour.toprates
  end

  def show
    @tour = Tour.infotour.find_by id: params[:id]
    @comments = Review.searches(params[:id]).page(params[:page]).per Settings.paginate.comment_page
    @booking = current_user.bookings.build if current_user
    @review = Review.new
    unless @tour
      redirect_to root_url
      flash[:info] = t "notfound"
    end
  end
end

app/helpers/mytours_helper.rb
module MytoursHelper
  def number_to_vnd number
     number_to_currency number, local: :en
  end
end

app/views/mytours/_comments.html.erb
<% @comments.each do |t| %>
  <div class="well">
    <div class="commentname">
      <%= t ".sentby" %><%= t.user.name %>
    </div>
    <div class="commentdes"><%= t.comment %></div>
    <span class="timestamp">
      <%= t ".post" %><%= time_ago_in_words(t.created_at) %><%= t ".ago" %>
    </span>
  </div>
<% end %>
<div>
  <span class="timesago">
    <%= t ".total" %><%= @comments.total_count %>
  </span>
</div>

app/views/mytours/_detailtour.html.erb
<div class="row">
  <div class="col-md-8 borrow1">
    <div class="borderele">
      <div class="product-item">
        <div class="showname"><h2><%= @tour.tour_name %></h2></div>
        <div class="imgleft">
          <%= image_tag(@tour.image, width: Settings.image.width,
          height: Settings.image.height) %>
        </div>
        <div class="row">
        <div class="col-xs-4 cpad">
          <%= rating_for @tour, "quality",disable_after_rate: false,
            enable_half: true, half_show: true, id: "oos", star_path: "/images/ratyrate" %>
          <div id="thanks"></div>
        </div>
        <div class="col-xs-6"></div>
        <div class="col-xs-2 shares">
          <div class="widget-body">
            <div class="beta-sales beta-lists">
             <%= social_share_button_tag(@tour.tour_name) %>
            </div>
          </div>
        </div>
        </div>
        <div class="col-md-3">
          <div class="showdes">
            <span class="glyphicon glyphicon-map-marker"></span>
            <%= @tour.destination %><br>
            <span class="glyphicon glyphicon-repeat"></span>
            <%= @tour.departure_date.to_date.strftime("%d-%m-%Y") %>
          </div>
        </div>
        <div class="col-md-5">
          <div class="showtime">
            <span class="glyphicon glyphicon-time"></span>
            <%= @tour.number_day %><%= t ".day" %>
            <%= @tour.number_night %><%= t ".night" %><br>
            <span class="glyphicon glyphicon-repeat"></span>
            <%= @tour.return_date.to_date.strftime("%d-%m-%Y") %>
          </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-4">
          <div class="showcode"><%= t ".tourcode" %><%= @tour.tour_code %></div>
        </div>
      </div>
      <div class="showsche"><%= t ".schedule" %></div>
      <div class="showplan well">
        <%= @tour.plan.description.html_safe %>
        <div class="row">
          <hr>
          <h4 class="showsche">Sevice Attach</h4>
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#insurrance">Insurrance</a></li>
            <li><a data-toggle="tab" href="#meal">Meal</a></li>
            <li><a data-toggle="tab" href="#tour-guide">Tour guide</a></li>
            <li><a data-toggle="tab" href="#ticket">Entrance tickets</a></li>
            <li><a data-toggle="tab" href="#car">Chuttle car</a></li>
          </ul>
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="insurrance">

              <%= @tour.sevice_attach.insurrance.to_s %>
            </div>
            <div role="tabpanel" class="tab-pane" id="meal">
              <%= @tour.sevice_attach.meal.to_s %>
            </div>
            <div role="tabpanel" class="tab-pane" id="tour-guide">
              <%= @tour.sevice_attach.tour_guide.to_s %>
            </div>
            <div role="tabpanel" class="tab-pane" id="ticket">
              <%= @tour.sevice_attach.entrance_tickets.to_s %>
            </div>
            <div role="tabpanel" class="tab-pane" id="car">
              <%= @tour.sevice_attach.chuttle_car.to_s %>
            </div>
          </div>
        </div>
        <div class="row">
          <hr>
          <h4 class="showsche">Slipulate</h4>
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#note">Note</a></li>
            <li><a data-toggle="tab" href="#cancel">Cancel tour</a></li>
          </ul>
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="insurrance">
              <%= @tour.stipulate.note.to_s %>
            </div>
            <div role="tabpanel" class="tab-pane" id="cancel">
              <%= @tour.stipulate.cancel_tour.to_s %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 well">
          <div id="formcomment">
            <% if current_user %>
              <%= form_for @review, remote: true do |r| %>
                <div class="row rowcomment">
                  <div class="col-xs-6">
                    <%= r.text_area :comment, placeholder: t(".comment"),
                      class: "form-control areatext", id: "clearcm" %>
                  </div>
                  <%= r.hidden_field :user_id, value: current_user.id, class: "form-control" %>
                  <%= r.hidden_field :tour_id, value: @tour.id, class: "form-control" %>
                </div>
                <%= r.submit t(".submit"), class: "btn btn-success
                  col-xs-2 submitcomment" %>
              <% end %>
            <% else %>
              <%= link_to t(".login"),  new_user_session_path, class: "btn btn-success logincomment" %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="comments"><%= render "comments" %></div>
      <div id="pagi"><%= paginate @comments, remote: true %></div>
    </div>
  </div>
  <div class="col-md-4">
    <% if current_user %>
      <div class="movebook">
        <%= form_for @booking do |f| %>
          <div class="alrow">
            <div class="row">
              <div class="col-md-7">
                <%= f.text_field :total_price, value: @tour.price,
                  class: "total_price totalprice", readonly: true %>
              </div>
              <div class="col-md-5"><%= t ".vnd" %></div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-5 numberr">
              <div class="guestrow"><%= t ".guest" %></div>
            </div>
            <div class="col-md-5 numberr">
              <%= f.hidden_field :tour_id, value: @tour.id, class: "form-control" %>
              <%= f.hidden_field :price, value: @tour.price, class: "form-control", id: "price" %>
              <div class="input-group">
                <span class="input-group-btn">
                  <span id="down" class="btn btn-default">
                    <span class="glyphicon glyphicon-minus"></span>
                  </span>
                </span>
                <%= f.text_field :number_customer, value: 1,
                  class: "form-control addcus", id: "customer", readonly: true %>
                <span class="input-group-btn">
                  <span id="up" class="btn btn-default spanadd">
                    <span class="glyphicon glyphicon-plus"></span>
                  </span>
                </span>
              </div>
            </div>
            <div class="col-md-2"></div>
          </div>

          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 btnsub">
              <%= f.submit t(".booktour"), class: "btn btn-danger" %>
            </div>
            <div class="col-md-3"></div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="borbook">
        <%= link_to t(".booking"),  new_user_session_path, class: "btn btn-danger
          loginbook" %>
      </div>
    <% end %>
  </div>
</div>

app/views/mytours/_filter.html.erb
<%= search_form_for @search, url: mytours_path, remote: true do |f| %>
  <div class="sortlink ">
    <%= t ".sort" %>
    <%= sort_link @search, :destination, "Place", {}, {remote: true,
      method: :get} %>
    <%= sort_link @search, :price, {}, {remote: true, method: :get} %>
  </div>
  <div class="input-group input-group-lg">
    <div class="form-group input-group-lg">
      <%= f.text_field :tour_name_cont, class: "form-control",placeholder: t(".input_keyword"), id: "searchinput", autocomplete: "off" %>
    </div>
    <div class="input-group-btn">
      <%= f.submit t(".search"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/mytours/_tours.html.erb
<div class="col-sm-12 padrow">
  <% @toptours.each do |top| %>
    <div class="col-xs-12 col-sm-4">
      <div class="product-item">
        <div class="pi-img-wrapper">
          <%= image_tag top.image, width: "380", height: "230" %>
          <div>
            <%= link_to mytour_path(id: top.id),
              class: "btn btn-default1 detailbtn" do %>
                <%= t ".detail" %>
                <span class="glyphicon glyphicon-chevron-right"></span>
            <% end %>
          </div>
        </div>
        <div class="row">
          <h4 class="name-tour">
            <%= link_to top.tour_name, mytour_path(id: top.id) %>
          </h4>
        </div>
        <div class="row">
          <div class="col-md-6">
        <div class="showdes">
          <h1>
            <span class="glyphicon glyphicon-map-marker"></span>
            <b><%= top.destination %></b><br>
            <span class="glyphicon glyphicon-road"></span>
            <%= top.departure_date.to_date.strftime("%d-%m-%Y") %>
          </h1>

          </div>
        </div>
        <div class="col-md-6">
          <h1><span class="glyphicon glyphicon-time"></span>
          <%= top.number_day %><%= t ".day" %>
          <%= top.number_night %><%= t ".night" %><br>
          <span class="glyphicon glyphicon-repeat"></span>
          <%= top.return_date.to_date.strftime("%d-%m-%Y") %>
          </h1>

        </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="pi-price">
              <%= number_to_vnd(top.price) %><%= t ".vnd" %>
            </div>
          </div>
          <div class="col-md-6">
            <%= image_tag "https://i.imgur.com/nWlIWae.png", class: "starrate" %>
            <%= top.avg.round 2 %><%= t ".point" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="row textsearch">
    <div class="col-md-2"></div>
    <div id="filter" class="col-md-8">
      <%= render "filter" %>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-8">
    <div id="pagination" class="pagechange">
      <%= paginate @tours, remote: true %>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>
<div class="row">
  <div class="col-md-5"></div>
  <div id="counter" class="col-md-3 pageinfo">
    <%= page_entries_info @tours %>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="col-sm-12">
  <% @tours.each do |tour| %>
    <div class="col-xs-12 col-sm-4">
      <div class="product-item">
        <div class="pi-img-wrapper">
          <%= image_tag tour.image, width: "380", height: "230" %>
          <div>
            <%= link_to mytour_path(id: tour.id),
              class: "btn btn-default1 detailbtn" do %>
                <%= t ".detail" %>
                <span class="glyphicon glyphicon-chevron-right"></span>
            <% end %>
          </div>
        </div>
        <div class="row">
          <h4 class="name-tour"><%= link_to tour.tour_name,
            mytour_path(id: tour.id)%></h4>
        </div>
        <div class="row">
          <div class="col-md-6">
        <div class="showdes">
          <h1>
            <span class="glyphicon glyphicon-map-marker"></span>
            <b><%= tour.destination %></b><br>
            <span class="glyphicon glyphicon-repeat"></span>
            <%= tour.departure_date.to_date.strftime("%d-%m-%Y") %>
          </h1>
          </div>
        </div>
        <div class="col-md-6">
          <h1><span class="glyphicon glyphicon-time"></span>
          <%= tour.number_day %><%= t ".day" %>
          <%= tour.number_night %><%= t ".night" %><br>
          <span class="glyphicon glyphicon-repeat"></span>
          <%= tour.return_date.to_date.strftime("%d-%m-%Y") %>
          </h1>
        </div>
        </div>
        <div class="pi-price">
          <%= number_to_vnd(tour.price) %><%= t ".vnd" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/mytours/home.html.erb
<section id="slider">
  <div class="slider">
    <div class="container">
      <div class="row">
        <div class="main_slider text-center">
          <div class="col-md-12">
            <div class="main_slider_content">
              <h1><%= t ".lifetrip" %></h1>
              <p><%= t ".quotelife" %></p>
              <button href="" class="btn-primary1"><%= t ".clickhere" %></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="abouts" class="abouts">
  <div class="container">
    <div class="row">
      <div class="abouts_content">
        <div class="col-md-6">
          <div class="row">
            <div class="col-md-6">
              <%= image_tag("img1.jpg", class: "img-responsive") %>
              <%= image_tag("img2.jpg", class: "img-responsive") %>
            </div>
            <div class="col-md-6">
              <%= image_tag("img3.jpg", class: "img-responsive") %>
              <%= image_tag("img4.jpg", class: "img-responsive") %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="single_abouts_text">
            <h4><%= t ".lifetrip" %></h4>
            <p><%= t ".tripquote" %></p>
            <%= link_to t(".clickhere"), mytours_path, class: "btn btn-primary1" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/mytours/index.html.erb
<section id="slider" class="slider">
  <div class="slider_overlay">
    <div class="container">
      <div id="tours">
        <%= render "tours" %>
      </div>
    </div>
  </div>
</section>

app/views/mytours/index.js.erb
$('#tours').html('<%= j render "tours" %>');
$('#filter').html('<%= j render "filter" %>');
$('#pagination').html('<%= j paginate(@tours, remote: true).to_s %>');
$('#counter').html('<%= j page_entries_info(@tours).to_s %>');

app/views/mytours/show.html.erb
<section class="detailshow">
  <div class="slider_overlay">
    <div class="container" id="detail">
      <%= render "detailtour" %>
    </div>
  </div>
</section>

app/views/mytours/show.js.erb
$('#detail').html('<%= j render "detailtour" %>');
$('#pagi').html('<%= j paginate(@comments, remote: true).to_s %>');