config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :admins do
    get "delete"
    get "booking"
  end
  get "list_admin", to: "admins#list_admin"
  get "list_user", to: "admins#list_user"
  resources :tours do
    get "delete"
  end
  root "mytours#home"
  post "/rate" , to: "rater#create", as: "rate"
  get "/booked", to: "bookings#booked"
  resources :users
  resources :mytours
  resources :bookings do
    get "delete"
  end
  resources :reviews, only: [:create, :destroy]
  resources :admins
end

app/views/admins/_edit.html.erb
<% provide :action_title, t(".edit")%>
<%= render "form_update" %>

app/views/admins/_flash.html.erb
<% flash.each do |messages_type, messages| %>
  <div class="alert alert-<%= messages_type %>" style="width: 100%">
    <p><%= messages %> <%= link_to @user.name, edit_admin_path(@user),
      remote: true %></p>
  </div>
<% end %>

app/views/admins/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @user, url: {controller: "admins"}, remote: true do |f| %>
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal">
          &times;</button>
        <h3 class="text-center font-weight-bold">
          <%= yield(:action_title) %>
        </h3>
        <div class="alert alert-danger" id="alert-danger-error">
          <ul class="errors "></ul>
        </div>
        <%= f.label :name, t("users.form.name") %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email, t("users.form.email") %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :sex, t("users.form.sex") %>
        <%= f.select :sex, User.sexes.keys %>

        <%= f.label :phone, t("users.form.phone") %>
        <%= f.text_field :phone, class: "form-control", placeholder: "+84" %>`

        <%= f.label :address, t("users.form.address") %>
        <%= f.text_field :address, class: "form-control" %>

        <%= f.label :password, t("users.form.password") %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation,
          t("users.form.password_confirmation") %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <div class="field">
            <%= f.check_box :admin, class: "remember_me" %>
            <span><%= f.label :admin %></span>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %><br>
        <%= link_to t("users.form.cancel"), "#", class: "btn",
          data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/_form_update.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @user, url: admin_path(@user), method: :patch,
      remote: true do |f| %>
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal">
          &times;</button>
        <h3 class="text-center font-weight-bold">
          <%= yield(:action_title) %>
        </h3>
        <div class="alert alert-danger" id="alert-danger-error">
          <ul class="errors "></ul>
        </div>
        <%= f.label :name, t("users.form.name") %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email, t("users.form.email") %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :sex, t("users.form.sex") %>
        <%= f.select :sex, User.sexes.keys %>

        <%= f.label :phone, t("users.form.phone") %>
        <%= f.text_field :phone, class: "form-control",
          placeholder: "+84" %>`

        <%= f.label :address, t("users.form.address") %>
        <%= f.text_field :address, class: "form-control" %>

        <div class="field">
            <%= f.check_box :admin, class: "remember_me" %>
            <span><%= f.label :admin %></span>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %><br>
        <%= link_to t("users.form.cancel"), "#", class: "btn",
          data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/_index.html.erb
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= user.address %></td>
    <td><%= user.sex %></td>
    <td>
      <%= link_to edit_admin_path(user), class: "btn btn-success", data: {toggle: "tooltip"}, title: "Edit",
        remote: true do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      <% unless user.admin? %>
        <%= link_to admin_booking_path(user), class: "btn btn-warning", data: {toggle: "tooltip"}, title: "Total tour of user booked",
          remote: true do %>
          <span class="glyphicon glyphicon-shopping-cart"></span>
          <span class="badge">
            <%= Booking.list_booking(user.id).size %></span>
        <% end %>
      <% end %>
      <% unless current_user.id == user.id %>
        <%= link_to admin_delete_path(user), class: "btn btn-danger", data: {toggle: "tooltip"}, title: "Delete",
          remote: true do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admins/_list.html.erb
<div class="row affix-row">
  <%= render "navbar_vertical" %>
  <div class="col-sm-9 col-md-10 affix-content">
    <div class="container-fluid">
      <div class="page-header">
        <h3><span class="glyphicon glyphicon-th-list"></span>
          <%= yield(:table_name) %></h3>
        <div class="row">
          <div class="col-md-3">
            <%= link_to t(".new_user"), new_admin_path, remote: true,
              class: "btn btn-primary" %>
          </div>

          <div class="col-md-3 col-md-offset-6">
            <div class="input-group">
              <input type="text" class="form-control" id="search-input"
                placeholder= "Search">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button"><span
                  class="glyphicon glyphicon-search" aria-hidden="true">
                  </span>
                </button>
              </span>
            </div>
          </div>
        </div>
        <div class="new-user"></div>
        <div id="flash">
        <hr>
        </div>
        <table class="table table-bordered table-striped table-hover table-bg" >
          <thead>
            <tr class="warning">
              <th><%= t "users.form.id" %></th>
              <th><%= t "users.form.name" %></th>
              <td><%= t "users.form.email" %></td>
              <td><%= t "users.form.phone" %></td>
              <th><%= t "users.form.address" %></th>
              <th><%= t "users.form.sex" %></th>
              <td><%= t "users.form.action" %></td>
            </tr>
          </thead>
          <tbody class="user-index" id="user-table">
            <%= render "index" %>
          </tbody>
        </table>
        <div id="paginate">
          <%= paginate @users %>
        </div>
      </div>
      <div id="user-modal" class="modal fade"></div>
    </div>
  </div>
</div>

app/views/admins/_save.js.erb
<% if @user.errors.any? %>
  document.getElementById("alert-danger-error").style.display = "block";
  <% @user.errors.full_messages.each do |message| %>
    $('ul.errors').append($('<li />').html('<%= message %>'))
  <% end %>
<% else %>
  $('#flash').html('<%= escape_javascript(render "flash") %>')
  $('.user-index').html('<%= escape_javascript(render "index") %>')
  $('#user-modal').modal('hide')
<% end %>

app/views/admins/booking.js.erb
$('#user-modal').html('<%= escape_javascript(render "booking") %>')
document.getElementById("alert-danger-error").style.display = "none";
$('#user-modal').modal('show')

app/views/admins/create.js.erb
<%= render "save" %>
<% if (@user.admin?) %>
  $('.total_admin').html('<%= User.list_admin.size %>')
<% else %>
  $('.total_user').html('<%= User.list_user.size %>')
<% end %>

app/views/admins/delete.js.erb
$('#user-modal').html('<%= escape_javascript(render "delete") %>')
$('#user-modal').modal('show')

app/views/admins/edit.js.erb
$('#user-modal').html('<%= escape_javascript(render "edit") %>')
document.getElementById("alert-danger-error").style.display = "none";
$('#user-modal').modal('show')

app/views/admins/list_user.html.erb
<% provide :table_name, t("admins.navbar_vertical.all_user") %>
<div class="list_user_index">
  <%= render "list" %>
</div>

app/views/admins/new.js.erb
$('#user-modal').html('<%= escape_javascript(render "new") %>')
document.getElementById("alert-danger-error").style.display = "none";
$('#user-modal').modal('show')

app/views/admins/update.js.erb
<%= render "save" %>