config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :admins do
    get "delete"
    get "booking"
  end
  get "list_admin", to: "admins#list_admin"
  get "list_user", to: "admins#list_user"
  resources :tours do
    get "delete"
  end
  root "mytours#home"
  post "/rate" , to: "rater#create", as: "rate"
  get "/booked", to: "bookings#booked"
  resources :users
  resources :mytours
  resources :bookings do
    get "delete"
  end
  resources :reviews, only: [:create, :destroy]
  resources :admins
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_one :sevice_attach, dependent: :destroy
  has_one :stipulate, dependent: :destroy
  has_one :plan
  validates :tour_name, :price, presence: true
  accepts_nested_attributes_for :plan, allow_destroy: true
  accepts_nested_attributes_for :sevice_attach, allow_destroy: true
  accepts_nested_attributes_for :stipulate, allow_destroy: true
  scope :all_tour, -> {select :id, :user_id, :tour_name, :tour_code, :destination,
      :number_day, :number_night, :departure_date, :return_date, :pickup_place,
      :price, :rate_avg, :created_by, :image}
  # mount_uploader :image, ImageUploader
  ratyrate_rateable "quality"
  scope :infotour, ->{select :id, :user_id, :tour_name, :pickup_place, :number_day,
    :number_night, :price, :destination, :tour_code, :image, :departure_date, :return_date}
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin

  def index
    @tours = Tour.all_tour.order("created_at DESC").page(params[:page]).per Settings.admins.per_page
  end

  def search

  end

  def show
    @tour = Tour.find params[:id]
  end

  def new
    @tour = current_user.tours.build
    @tour.build_plan
    @tour.build_stipulate
    @tour.build_sevice_attach
  end

  def create
    @tour = current_user.tours.build tour_params
    @tour.user = current_user
    @tour.created_by = User.find(@tour.user_id).name
    if @tour.save
      flash.now[:success] = "Tour has been created have name: (can click to edit)"
    else
      flash.now[:danger] = "Tour can't create"
    end
    @tour.tour_name = "Tour #{@tour.destination} #{@tour.number_day}N#{@tour.number_night}D: #{@tour.tour_name}"
    @tour.tour_code = "TFE-#{@tour.departure_date.to_date.strftime("%d%m%Y")}-#{@tour.id}"
    @tour.save
    @tours = Tour.all_tour.order("created_at DESC").page(params[:page]).per Settings.admins.per_page
  end

  def edit
    @tour = Tour.find params[:id]
  end

  def update
    @tours = Tour.all_tour.order("created_at DESC").page(params[:page]).per Settings.admins.per_page
    @tour = Tour.find params[:id]
    @tour.user = current_user
    if @tour.update_attributes tour_params
      flash.now[:success] = "Tour has been updated have name: (can click to edit)"
    else
      flash.now[:danger] = "Tour can't edit"
    end
  end

  def delete
    @tour = Tour.find params[:tour_id]
  end

  def destroy
    @tours = Tour.all_tour.order("created_at DESC").page(params[:page]).per Settings.admins.per_page
    @tour = Tour.find params[:id]
    @tour.destroy
    if @tour.destroyed?
      flash.now[:danger] = "You was destroyed have name: "
    end
  end

  private

  def tour_params
    params.require(:tour).permit :tour_name, :tour_code, :destination,
      :number_day, :number_night, :departure_date, :return_date, :pickup_place,
      :price, :rate_avg, :created_by, :image,
      plan_attributes: [:id, :description],
      stipulate_attributes: [:id, :note, :cancel_tour],
      sevice_attach_attributes: [:id, :insurrance, :meal, :tour_guide,
      :entrance_tickets, :chuttle_car]
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_delete.html.erb
<% provide :title_action, "Delete" %>
<div class="modal-dialog modal-lg">
  <div class="modal-content">
  <div class="modal-header">
    <h4>
      <span class="glyphicon glyphicon-warning-sign"></span>
      <span class="glyphicon glyphicon-warning-sign"></span>
      <span class="glyphicon glyphicon-warning-sign"></span>
      Delete
    </h4>
  </div>
    <div class="modal-body">
      <ul class="errors"></ul>Comfirm delete<b>
        <%= @tour.tour_name %></b> have information?
      <table class="table">
        <thead>
          <tr class="danger">
            <th>ID</th>
            <th>Code</th>
            <th>Name</th>
            <th>Destination</th>
            <th>Date</th>
            <th>pick up place</th>
            <th>price per person</th>
            <th>Rate AVG</th>
            <th>Create by</th>
          </tr>
        </thead>
        <tbody>
          <tr class="warning">
            <td><%= @tour.id %></td>
            <td><%= @tour.tour_code %></td>
            <td><%= @tour.tour_name %></td>
            <td><%= @tour.destination %></td>
            <td>
              Total days: <%= @tour.number_day %>D<%= @tour.number_night %>N<br>
              Departure: <%= @tour.departure_date %><br>
              Return: <%= @tour.return_date %>
            </td>
            <td><%= @tour.pickup_place %></td>
            <td><%= @tour.price %></td>
            <td><%= @tour.rate_avg %></td>
            <td><%= @tour.user_id %></td>
          </tr>

        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <%= link_to t(".delete"), tour_path(@tour), method: :delete,
        remote: true, class: "btn btn-danger" %>
      <%= link_to t(".cancel"), "#", class: "btn btn-default",
        data: {dismiss: "modal"} %>
    </div>
  </div>
</div>

app/views/tours/_edit.html.erb
<% provide :title_action, "Edit #{@tour.tour_name}"%>
<div class="container">
  <%= render "form" %>
</div>

app/views/tours/_flash.html.erb
<% flash.each do |messages_type, messages| %>
  <div class="alert alert-<%= messages_type %>" style="width: 100%">
    <p><%= messages %>
      <% if @tour.destroyed? %>
        <%= @tour.tour_name %>
      <% else %>
        <%= link_to @tour.tour_name, edit_tour_path(@tour),
      remote: true %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/tours/_form.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><%= yield :title_action %></h4>
    </div>
    <div class="modal-body">
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#info-basic">Info basic</a></li>
        <li><a data-toggle="tab" href="#description">Description</a></li>
        <li><a data-toggle="tab" href="#sevice">Sevice Attach</a></li>
        <li><a data-toggle="tab" href="#slipulate">Slipulate</a></li>
      </ul>
      <div class="alert alert-danger" id="alert-danger-error">
        <ul class="errors "></ul>
      </div>
      <%= form_for @tour, :html => {:multipart => true}, remote: true do |f|%>
        <div class="tab-content">
          <div id="info-basic" class="tab-pane fade in active">
            <%= f.label :tour_name %>
            <%= f.text_field :tour_name, class: "form-control" %>
            <div class="row">
              <div class="col-md-3">
                <%= f.label :departure_date %>
                <%#= f.text_field :departure_date, data: {provide: "datepicker"}, class: "form-control" %>
                <%= f.date_field :departure_date, class: "form-control" %>
              </div>
              <div class="col-md-2">
                <%= f.label :number_day %>
                <%= f.select :number_day, 1..15, {}, class: "form-control" %>
              </div>
              <div class="col-md-2">
                <%= f.label :number_night %>
                <%= f.select :number_night, 1..15, {}, class: "form-control" %>
              </div>
              <div class="col-md-2">
                <%= f.label :pickup_place %>
                <%= f.text_field :pickup_place, class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= f.label :price %>
                <div class="input-group">
                  <%= f.text_field :price, class: "form-control", aria: {describedby: "basic-addon2"} %>
                  <span class="input-group-addon" id="basic-addon2">VND</span>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3">
                <%= f.label :return_date %>
                <%= f.text_field :return_date, class: "form-control", readonly: true %>
              </div>
              <div class="col-md-3">
                <%= f.label :destination %>
                <%= f.text_field :destination, class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= f.label :image %>
                <%= f.file_field :image, class: "fallback" %>
              </div>
            </div>

          </div>
          <div id="description" class="tab-pane fade">
            <%= f.fields_for :plan do |k| %>
              <%= k.label :description %>
              <%= k.cktext_area :description, rows: 10 %>
            <% end %>
          </div>
          <div id="sevice" class="tab-pane fade">
            <%= f.fields_for :sevice_attach do |l| %>
              <div class="row">
                <div class="col-md-6">
                  <%= l.label :insurrance %>
                  <%= l.text_area :insurrance, rows: 5 %>
                </div>
                <div class="col-md-6">
                  <%= l.label :meal %>
                  <%= l.text_area :meal, rows: 5 %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <%= l.label :tour_guide %>
                  <%= l.text_area :tour_guide, rows: 5 %>
                </div>
                <div class="col-md-6">
                  <%= l.label :entrance_tickets %>
                  <%= l.text_area :entrance_tickets, rows: 5 %>
                </div>
              </div>
              <%= l.label :chuttle_car %>
              <%= l.text_area :chuttle_car, rows: 5 %>
            <% end %>
          </div>
          <div id="slipulate" class="tab-pane fade">
            <%= f.fields_for :stipulate do |m| %>
              <div class="row">
                <div class="col-md-6">
                  <%= m.label :note %>
                  <%= m.text_area :note, rows: 5 %>
                </div>
                <div class="col-md-6">
                  <%= m.label :cancel_tour %>
                  <%= m.text_area :cancel_tour, rows: 5 %>
                </div>
              </div>
            <% end %>
            <%= f.submit class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#tour_number_day").click(function(){
      document.getElementById("tour_number_night").value = Number(document.getElementById("tour_number_day").value) + Number(1);
      set_return_day();
    });
    $("#tour_number_night").click(function(){
      if($("#tour_number_night").val() > Number($("#tour_number_day").val()) + Number(1)){
        $("#tour_number_night").val(Number($("#tour_number_day").val()) + Number(1));
        window.alert("Number night only less than or equal to number day crease one");
      } else if ($("#tour_number_night").val() < Number($("#tour_number_day").val()) - Number(1)) {
        $("#tour_number_night").val(Number($("#tour_number_day").val()) - Number(1));
        window.alert("Number night only greater than or equal to number day crease one");
      }
      set_return_day();
    });
    $("#tour_departure_date").change(function(){
      if(new Date($("#tour_departure_date").val()) < new Date()) {
        var myDate = new Date();
        $("#tour_departure_date").val(myDate.toISOString().split("T")[0]);
        window.alert("You must choose at the moment");
        set_return_day();
      }
    });
    function set_return_day(){
      var nights = parseInt($('#tour_number_night').val());
      var return_date_js = new Date($('#tour_departure_date').val());
      return_date_js.setDate(return_date_js.getDate() + nights);
      document.getElementById("tour_return_date").value = return_date_js.toISOString().split("T")[0];
    }
  });
</script>

app/views/tours/_new.html.erb
<% provide :title_action, "Create tour"%>
<div class="container">
  <%= render "form" %>
</div>

app/views/tours/_record.html.erb
<% @tours.each do |tour| %>
  <tr>
    <td><%= tour.id %></td>
    <td><%= tour.tour_code %></td>
    <td><%= tour.tour_name %></td>
    <td><%= tour.destination %></td>
    <td>
      Total days: <%= tour.number_day %>D<%= tour.number_night %>N <br>
      Departure: <%= tour.departure_date %><br>
      Return: <%= tour.return_date %>
    </td>
    <td><%= tour.pickup_place %></td>
    <td><%= number_to_vnd tour.price %></td>
    <td>
      <%= tour.created_by %><br>
      <%#= image_tag tour.image_title.url if tour.image_title? %>
    </td>
    <td>
      <%= link_to edit_tour_path(tour), class: "btn btn-success", id: "edit_tour",
        remote: true do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      <%= link_to tour_delete_path(tour), class: "btn btn-danger",
        remote: true do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/tours/create.js.erb
<%= render "save" %>

app/views/tours/delete.js.erb
$('#tour-modal').html('<%= escape_javascript(render "delete") %>')
$('#tour-modal').modal('show')

app/views/tours/destroy.js.erb
$('#flash').html('<%= escape_javascript(render "flash") %>')
$('.tour-index').html('<%= escape_javascript(render "record") %>')
$('#tour-modal').modal('hide')
$('.total_tour').html('<%= Tour.all_tour.size %>')

app/views/tours/edit.js.erb
$('#tour-modal').html('<%= j render "edit" %>')
document.getElementById("alert-danger-error").style.display = "none";
$('#tour-modal').modal('show')

app/views/tours/index.html.erb
<div class="row">
  <section class="navbar-vertical">
    <%= render "admins/navbar_vertical" %>
  </section>
  <section class="main-list">
    <div class="col-sm-9 col-md-10 affix-content">
      <div class="container-fluid">
        <div class="page-header">
          <h3><span class="glyphicon glyphicon-th-list"></span> List Tour</h3>
          <div class="row">
            <div class="col-md-3">
              <%= link_to "Create tour", new_tour_path, id: "new_tour", remote: true,
                class: "btn btn-success" %>
            </div>
            <div class="col-md-6">

            </div>
            <div class="col-md-3">
              <div class="input-group">
                <input type="text" class="form-control" id="search-input"
                  placeholder= "Search">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button"><span
                    class="glyphicon glyphicon-search" aria-hidden="true">
                    </span>
                  </button>
                </span>
              </div>
            </div>

          </div>
          <hr>
          <div class="new-tour"></div>
          <div id="flash"></div>
          <table class="table table-bordered table-striped table-hover" >
            <thead>
              <tr class="warning">
                <th>ID</th>
                <th>Code</th>
                <th>Name</th>
                <th>Destination</th>
                <th>Date</th>
                <th>pick up place</th>
                <th>price/P (Vnd)</th>
                <th>Create by</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody class="tour-index">
              <%= render "record" %>
            </tbody>
          </table>
          <div id="paginate">
            <%= paginate @tours%>
          </div>
        </div>
        <div id="tour-modal" class="modal fade"></div>
      </div>
    </div>
  </section>
</div>

app/views/tours/new.js.erb
$('#tour-modal').html('<%= j render "new" %>')
document.getElementById("alert-danger-error").style.display = "none";
$('#tour-modal').modal('show')

app/views/tours/test.html.erb
<% if @tour.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.error_messages.contains" %> <%= pluralize @tour.errors.count, t("shared.error_messages.error") %>
    </div>
    <ul>
      <% @tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @tour do |f|%>
  <%= f.label :tour_name %>
  <%= f.text_field :tour_name, class: "form-control" %>
  <%= f.fields_for :plan do |k| %>
    <%= k.label :description %>
    <%= k.cktext_area :description, rows: 10 %>
  <% end %>
  <h3>Sevice Attach</h3>
  <hr>
  <%= f.fields_for :sevice_attach do |l| %>
    <div class="row">
      <div class="col-md-6">
        <%= l.label :insurrance %>
        <%= l.text_area :insurrance, rows: 5 %>
      </div>
      <div class="col-md-6">
        <%= l.label :meal %>
        <%= l.text_area :meal, rows: 5 %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= l.label :tour_guide %>
        <%= l.text_area :tour_guide, rows: 5 %>
      </div>
      <div class="col-md-6">
        <%= l.label :entrance_tickets %>
        <%= l.text_area :entrance_tickets, rows: 5 %>
      </div>
    </div>
    <%= l.label :chuttle_car %>
    <%= l.text_area :chuttle_car, rows: 5 %>
  <% end %>
  <h3>Stipulate</h3>
  <hr>
  <%= f.fields_for :stipulate do |m| %>
    <div class="row">
      <div class="col-md-6">
        <%= m.label :note %>
        <%= m.text_area :note, rows: 5 %>
      </div>
      <div class="col-md-6">
        <%= m.label :cancel_tour %>
        <%= m.text_area :cancel_tour, rows: 5 %>
      </div>
    </div>
  <% end %>
  <%= f.submit class: "btn btn-warning" %>
<% end %>

app/views/tours/update.js.erb
<%= render "save", formats: [:html] %>