config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :admins do
    get "delete"
    get "booking"
  end
  get "list_admin", to: "admins#list_admin"
  get "list_user", to: "admins#list_user"
  resources :tours do
    get "delete"
  end
  root "mytours#home"
  post "/rate" , to: "rater#create", as: "rate"
  get "/booked", to: "bookings#booked"
  resources :users
  resources :mytours
  resources :bookings do
    get "delete"
  end
  resources :reviews, only: [:create, :destroy]
  resources :admins
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer text-center">
  <%= t ".copyright" %>
</footer>

app/views/layouts/_header.html.erb
<header id="home">
  <div class="main_menu_bg">
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid" id="colla">
            <div class="navbar-header">
              <ul class="nav navbar-nav navbar-left">
                <li class="name-web"><%= link_to "TourFE", root_path %></li>
              </ul>
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to t(".list_tour"), mytours_path,
                  class: "booking" %></li>
                <% if current_user %>
                  <% if current_user.admin? %>
                    <li><%= link_to "Manager", list_user_path %></li>
                  <% else %>
                    <li><%= link_to booked_path do %>
                      <span class="glyphicon glyphicon-shopping-cart"></span>
                      <span class="badge pull-right">
                        <%= Booking.list_booking(current_user.id).size %>
                      </span>
                    <% end %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to edit_user_registration_path do %>
                      <span class="glyphicon glyphicon-user"></span>
                      <%= current_user.email %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <span class="glyphicon glyphicon-off"></span>
                      <%= t ".signout" %>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to new_user_registration_path do %>
                      <span class="glyphicon glyphicon-user"></span>
                      <%= t ".signup" %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_session_path do %>
                      <span class="glyphicon glyphicon-user"></span>
                      <%= t ".login" %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %> </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag asset_path('/favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="content">
        <% flash.each do |messages_type, messages| %>
          <div class="alert alert-<%= messages_type %>">
            <%= messages %>
          </div>
        <% end %>
        <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>